create table if not exists public.countries (
  id uuid primary key default gen_random_uuid(),
  slug text not null unique,
  name text not null unique,
  iso_code char(2) not null unique,
  hero_image_url text,
  description text,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.destinations (
  id uuid primary key default gen_random_uuid(),
  country_id uuid not null references public.countries(id) on delete cascade,
  region_id uuid,
  slug text not null unique,
  name text not null,
  destination_type text not null check (destination_type in ('park','city','beach','reserve','mountain','island','cultural','mixed')),
  summary text,
  description text,
  latitude numeric(9,6),
  longitude numeric(9,6),
  hero_image_url text,
  best_months text[] not null default '{}',
  tags text[] not null default '{}',
  is_published boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.operators (
  id uuid primary key default gen_random_uuid(),
  slug text not null unique,
  name text not null,
  country_id uuid references public.countries(id) on delete set null,
  description text,
  website_url text,
  email citext,
  phone text,
  whatsapp_number text,
  logo_url text,
  years_in_operation int,
  languages text[] not null default '{}',
  specialties text[] not null default '{}',
  verified_status text not null default 'pending' check (verified_status in ('pending','verified','rejected')),
  review_count int not null default 0,
  average_rating numeric(2,1),
  response_time_hours int,
  cancellation_policy text,
  payment_policy text,
  is_published boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.guides (
  id uuid primary key default gen_random_uuid(),
  slug text not null unique,
  operator_id uuid references public.operators(id) on delete set null,
  country_id uuid references public.countries(id) on delete set null,
  destination_id uuid references public.destinations(id) on delete set null,
  full_name text not null,
  bio text,
  email citext,
  phone text,
  whatsapp_number text,
  avatar_url text,
  languages text[] not null default '{}',
  specialties text[] not null default '{}',
  years_experience int,
  verified_status text not null default 'pending' check (verified_status in ('pending','verified','rejected')),
  review_count int not null default 0,
  average_rating numeric(2,1),
  response_time_hours int,
  is_published boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.accommodations (
  id uuid primary key default gen_random_uuid(),
  slug text not null unique,
  operator_id uuid references public.operators(id) on delete set null,
  destination_id uuid references public.destinations(id) on delete set null,
  country_id uuid references public.countries(id) on delete set null,
  name text not null,
  accommodation_type text not null check (accommodation_type in ('hotel','lodge','camp','tented_camp','villa','guesthouse')),
  summary text,
  description text,
  location_label text,
  address_line_1 text,
  latitude numeric(9,6),
  longitude numeric(9,6),
  hero_image_url text,
  amenities text[] not null default '{}',
  room_types text[] not null default '{}',
  board_basis text[] not null default '{}',
  check_in_time text,
  check_out_time text,
  child_policy text,
  cancellation_policy text,
  payment_policy text,
  verified_status text not null default 'pending' check (verified_status in ('pending','verified','rejected')),
  review_count int not null default 0,
  average_rating numeric(2,1),
  response_time_hours int,
  is_featured boolean not null default false,
  is_published boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.accommodation_units (
  id uuid primary key default gen_random_uuid(),
  accommodation_id uuid not null references public.accommodations(id) on delete cascade,
  unit_name text not null,
  unit_type text not null check (unit_type in ('single','double','twin','suite','family','tent','villa')),
  capacity_adults int not null default 2,
  capacity_children int not null default 0,
  base_price numeric(12,2),
  currency char(3) not null default 'USD',
  amenities text[] not null default '{}',
  inventory_count int not null default 0,
  is_published boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.itineraries (
  id uuid primary key default gen_random_uuid(),
  slug text not null unique,
  operator_id uuid references public.operators(id) on delete set null,
  country_id uuid references public.countries(id) on delete set null,
  destination_id uuid references public.destinations(id) on delete set null,
  title text not null,
  itinerary_type text not null check (itinerary_type in ('short','long','private','group','luxury','budget','family','romantic','custom')),
  summary text,
  description text,
  duration_days int not null check (duration_days > 0),
  nights int not null default 0,
  from_price numeric(12,2),
  currency char(3) not null default 'USD',
  price_label text default 'per person',
  inclusions text[] not null default '{}',
  exclusions text[] not null default '{}',
  highlights text[] not null default '{}',
  available_months text[] not null default '{}',
  hero_image_url text,
  max_group_size int,
  min_group_size int default 1,
  verified_status text not null default 'pending' check (verified_status in ('pending','verified','rejected')),
  review_count int not null default 0,
  average_rating numeric(2,1),
  response_time_hours int,
  cancellation_policy text,
  payment_policy text,
  is_featured boolean not null default false,
  is_published boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.itinerary_days (
  id uuid primary key default gen_random_uuid(),
  itinerary_id uuid not null references public.itineraries(id) on delete cascade,
  day_number int not null,
  title text not null,
  summary text,
  accommodation_id uuid references public.accommodations(id) on delete set null,
  meals_included text[] not null default '{}',
  activities text[] not null default '{}',
  drive_time_label text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(itinerary_id, day_number)
);
